export type PersonaKey = 'employee' | 'admin' | 'manager'
export type FlowType = 'run' | 'output'

type FieldItem = {
  label: string
  val?: string
  filled?: boolean
  select?: boolean
  full?: boolean
  req?: boolean
  ph?: string
}

type TilesItem = {
  i: string
  tt: string
  ts: string
  badge?: string
}

type KpiItem = {
  kv: string
  kl: string
  tone?: 'warn' | 'err' | 'ok'
}

type BarItem = {
  label: string
  val: string
  pct: number
  tone?: 't-net' | 't-tax' | 't-ded' | 't-blue' | 't-gross'
}

type TimelineStep = {
  label: string
  sub?: string
  state?: 'done' | 'cur'
}

type TrendItem = {
  label: string
  num: number
  text: string
  hl?: boolean
}

type TableCol = {
  name: string
  num?: boolean
}

type PayslipItem = {
  label: string
  cur: string
  ytd: string
}

type DocsItem = {
  n: string
  d: string
  badge: 'ok' | 'sign'
  bl: string
}

type ReviewRow = [string, string]

type ChecklistItem = {
  c: string
  s: 'done' | 'prog' | 'todo'
  st: string
}

type AlertsItem = {
  sev: 'error' | 'warn' | 'info'
  icon: string
  title: string
  sub: string
  ab: string
}

type ChoicesItem = {
  l: string
  s: string
  sel?: boolean
}

type ActionsItem = {
  label: string
  kind?: 'primary' | 'ghost'
}

export type Block =
  | { t: 'fields'; title?: string; items: FieldItem[] }
  | { t: 'tiles'; title?: string; items: TilesItem[] }
  | { t: 'kpis'; title?: string; items: KpiItem[] }
  | { t: 'hero'; label: string; value: string; sub?: string; status?: string; delta?: string; deltaClass?: 'up' | 'down' | 'flat' }
  | { t: 'bars'; title?: string; items: BarItem[] }
  | { t: 'timeline'; title?: string; steps: TimelineStep[] }
  | {
    t: 'table'
    title?: string
    cols: TableCol[]
    rows: string[][]
    totals?: string[]
    cap?: string
  }
  | {
    t: 'trend'
    title?: string
    items: TrendItem[]
  }
  | {
    t: 'payslip'
    period: string
    payDate: string
    status: string
    earnings: PayslipItem[]
    gross: { cur: string; ytd: string }
    deductions: PayslipItem[]
    ded: { cur: string; ytd: string }
    net: { cur: string; ytd: string }
  }
  | { t: 'docs'; title?: string; items: DocsItem[] }
  | { t: 'review'; title?: string; rows: ReviewRow[] }
  | { t: 'checklist'; title?: string; items: ChecklistItem[] }
  | { t: 'alerts'; title?: string; items: AlertsItem[] }
  | { t: 'choices'; title?: string; items: ChoicesItem[] }
  | { t: 'actions'; items: ActionsItem[] }
  | { t: 'note'; warn?: boolean; text: string }
  | { t: 'esign'; sig: string; lbl: string }
  | { t: 'complete'; h: string; p: string }

export interface Step {
  title: string
  tag: string
  tagClass?: string
  crumb: string
  intro: string
  blocks: Block[]
}

export interface Persona {
  label: string
  who: string
  ctx: string
  steps: Step[]
}

const F = (label: string, val: string, opt: Partial<FieldItem> = {}): FieldItem => ({ label, val, ...opt })

export const OUTPUT_PERSONAS: Record<PersonaKey, Persona> = {
  employee: {
    label: 'Employee',
    who: 'Alex Morgan',
    ctx: 'Payroll output',
    steps: [
      {
        title: 'Pay Results — Summary',
        tag: 'Result',
        tagClass: 'result',
        crumb: 'My Pay',
        intro: 'The headline outcome of this payroll run: what you were paid, when, and where it went.',
        blocks: [
          {
            t: 'hero',
            label: 'Net pay — Period 12',
            value: '$2,606.78',
            sub: 'Pay date Fri, Jun 20, 2025 · Bi-weekly',
            status: 'Deposited',
            delta: '▲ $22.66 vs last period',
            deltaClass: 'up',
          },
          {
            t: 'bars',
            title: 'Where your gross pay went ($3,733.46)',
            items: [
              { label: 'Net pay', val: '$2,606.78 · 69.8%', pct: 69.8, tone: 't-net' },
              { label: 'Taxes (federal, SS, Medicare)', val: '$797.71 · 21.4%', pct: 21.4, tone: 't-tax' },
              { label: 'Other deductions (401k, benefits)', val: '$328.97 · 8.8%', pct: 8.8, tone: 't-ded' },
            ],
          },
          {
            t: 'timeline',
            title: 'Pay status',
            steps: [
              { label: 'Calculated', sub: 'Jun 18', state: 'done' },
              { label: 'Approved', sub: 'Jun 19', state: 'done' },
              { label: 'Posted', sub: 'Jun 19', state: 'done' },
              { label: 'Paid', sub: 'Jun 20', state: 'done' },
            ],
          },
        ],
      },
      {
        title: 'Payslip (PDF)',
        tag: 'Document',
        tagClass: 'doc',
        crumb: 'My Pay',
        intro: 'Your formal pay statement, generated by the run and archived to your profile. Download or email a copy.',
        blocks: [
          {
            t: 'payslip',
            period: 'Jun 7 – Jun 20, 2025 · Period 12 of 26',
            payDate: 'Fri, Jun 20, 2025',
            status: 'Paid',
            earnings: [
              { label: 'Base Salary', cur: '$3,538.46', ytd: '$42,461.52' },
              { label: 'Overtime', cur: '$145.00', ytd: '$612.00' },
              { label: 'Remote Allowance', cur: '$50.00', ytd: '$600.00' },
            ],
            gross: { cur: '$3,733.46', ytd: '$43,673.52' },
            deductions: [
              { label: 'Federal Income Tax', cur: '$512.10', ytd: '$6,021.40' },
              { label: 'Social Security', cur: '$231.47', ytd: '$2,707.76' },
              { label: 'Medicare', cur: '$54.14', ytd: '$633.27' },
              { label: 'State Income Tax (TX)', cur: '$0.00', ytd: '$0.00' },
              { label: '401(k) — 5%', cur: '$186.67', ytd: '$2,183.68' },
              { label: 'Medical & Dental', cur: '$142.30', ytd: '$1,707.60' },
            ],
            ded: { cur: '$1,126.68', ytd: '$13,253.71' },
            net: { cur: '$2,606.78', ytd: '$30,419.81' },
          },
          {
            t: 'actions',
            items: [
              { label: 'Download PDF', kind: 'primary' },
              { label: 'Email to me', kind: 'ghost' },
            ],
          },
        ],
      },
      {
        title: 'Year-to-Date Overview',
        tag: 'Result',
        tagClass: 'result',
        crumb: 'My Pay',
        intro: 'Your cumulative pay and withholding for 2025 so far.',
        blocks: [
          {
            t: 'kpis',
            items: [
              { kv: '$43,673.52', kl: 'YTD gross' },
              { kv: '$9,362.43', kl: 'YTD taxes', tone: 'warn' },
              { kv: '$3,891.28', kl: 'YTD deductions' },
              { kv: '$30,419.81', kl: 'YTD net', tone: 'ok' },
            ],
          },
          {
            t: 'bars',
            title: 'YTD distribution',
            items: [
              { label: 'Net pay', val: '$30,419.81 · 69.7%', pct: 69.7, tone: 't-net' },
              { label: 'Taxes', val: '$9,362.43 · 21.4%', pct: 21.4, tone: 't-tax' },
              { label: 'Deductions', val: '$3,891.28 · 8.9%', pct: 8.9, tone: 't-ded' },
            ],
          },
        ],
      },
      {
        title: 'Payment Confirmation',
        tag: 'Result',
        tagClass: 'result',
        crumb: 'My Pay',
        intro: 'Proof of deposit for this period — a remittance advice you can save for your records.',
        blocks: [
          {
            t: 'review',
            title: 'Remittance advice',
            rows: [
              ['Amount', '$2,606.78'],
              ['Method', 'ACH — direct deposit'],
              ['Deposited to', 'Checking ••••4821'],
              ['Value date', 'Jun 20, 2025'],
              ['Reference', 'PAY-2025-12-000293'],
              ['Status', 'Completed'],
            ],
          },
          {
            t: 'note',
            text: 'If a deposit looks wrong, contact payroll with the reference above — don\'t wait for the next cycle.',
          },
        ],
      },
      {
        title: 'Pay History & Trend',
        tag: 'Result',
        tagClass: 'result',
        crumb: 'My Pay',
        intro: 'How your net pay has moved across recent periods.',
        blocks: [
          {
            t: 'trend',
            title: 'Net pay — last 6 periods',
            items: [
              { label: 'P7', num: 2571.4, text: '$2,571' },
              { label: 'P8', num: 2571.4, text: '$2,571' },
              { label: 'P9', num: 2571.4, text: '$2,571' },
              { label: 'P10', num: 2584.12, text: '$2,584' },
              { label: 'P11', num: 2584.12, text: '$2,584' },
              { label: 'P12', num: 2606.78, text: '$2,607', hl: true },
            ],
          },
          {
            t: 'table',
            title: 'Recent payslips',
            cols: [
              { name: 'Period' },
              { name: 'Pay date' },
              { name: 'Gross', num: true },
              { name: 'Net', num: true },
            ],
            rows: [
              ['Period 12', 'Jun 20, 2025', '$3,733.46', '$2,606.78'],
              ['Period 11', 'Jun 6, 2025', '$3,700.12', '$2,584.12'],
              ['Period 10', 'May 23, 2025', '$3,700.12', '$2,584.12'],
              ['Period 9', 'May 9, 2025', '$3,683.20', '$2,571.40'],
            ],
          },
        ],
      },
      {
        title: 'Tax Documents (Year-End)',
        tag: 'Document',
        tagClass: 'doc',
        crumb: 'Documents',
        intro: 'Your annual statements, produced by year-end payroll processing.',
        blocks: [
          {
            t: 'docs',
            items: [
              { n: 'Form W-2 — 2024', d: 'Issued Jan 28, 2025 · electronic', badge: 'ok', bl: 'Download' },
              { n: 'Form W-2 — 2023', d: 'Available', badge: 'ok', bl: 'Download' },
            ],
          },
          {
            t: 'review',
            title: 'Form W-2 (2024) — key boxes',
            rows: [
              ['Box 1 — Wages, tips', '$86,400.00'],
              ['Box 2 — Federal income tax', '$11,980.00'],
              ['Box 3 — Social Security wages', '$89,200.00'],
              ['Box 4 — Social Security tax', '$5,530.40'],
              ['Box 5 — Medicare wages', '$89,200.00'],
              ['Box 6 — Medicare tax', '$1,293.40'],
            ],
          },
        ],
      },
      {
        title: 'Tax Withholding (Form W-4)',
        tag: 'Task',
        tagClass: 'task',
        crumb: 'Pay',
        intro: 'Tell payroll how much federal tax to withhold. State withholding appears here only if your work state requires it — Texas has no state income tax.',
        blocks: [
          {
            t: 'fields',
            title: 'Federal elections',
            items: [
              F('Filing status', 'Single or married filing separately', { filled: true, full: true, req: true }),
              F('Multiple jobs / spouse works', 'No', { filled: true }),
              F('Dependents amount', '$0.00', { filled: true }),
              F('Extra withholding', '', { ph: '$0.00' }),
            ],
          },
          {
            t: 'esign',
            sig: 'Alex Morgan',
            lbl: 'I certify these withholding elections are correct.',
          },
        ],
      },
      {
        title: 'Deductions',
        tag: 'Review',
        tagClass: 'review',
        crumb: 'Pay',
        intro: 'A breakdown of what’s deducted from your pay each period. Benefit elections are managed in the Benefits area.',
        blocks: [
          {
            t: 'checklist',
            title: 'Recurring deductions',
            items: [
              { c: '401(k) retirement — 5% pre-tax', s: 'done', st: '$186.67' },
              { c: 'Medical & dental premium', s: 'done', st: '$142.30' },
              { c: 'Federal income tax', s: 'done', st: '$512.10' },
              { c: 'FICA (Social Security + Medicare)', s: 'done', st: '$285.61' },
            ],
          },
          {
            t: 'note',
            text: 'Garnishments or one-time deductions, if any, appear here with their reference details.',
          },
        ],
      },
      {
        title: 'Year-End Documents',
        tag: 'Task',
        tagClass: 'task',
        crumb: 'Documents',
        intro: 'Access your annual tax statements and choose how you’d like to receive them.',
        blocks: [
          {
            t: 'docs',
            items: [
              { n: 'Form W-2 — 2024', d: 'Available · issued Jan 28, 2025', badge: 'ok', bl: 'Download' },
              { n: 'Form W-2 — 2023', d: 'Available', badge: 'ok', bl: 'Download' },
            ],
          },
          {
            t: 'choices',
            title: 'Delivery preference',
            items: [
              { l: 'Electronic only (recommended)', s: 'Get notified when your W-2 is ready', sel: true },
              { l: 'Electronic and mailed paper copy', s: '', sel: false },
            ],
          },
        ],
      },
      {
        title: 'All set',
        tag: 'Done',
        tagClass: 'done',
        crumb: 'Done',
        intro: '',
        blocks: [
          {
            t: 'complete',
            h: 'Your payroll information is up to date',
            p: 'You can return to any tile anytime. Pending changes show under your To-Do until payroll approves them.',
          },
          {
            t: 'checklist',
            title: 'Pending with payroll',
            items: [
              { c: 'Bank account change', s: 'prog', st: 'Awaiting approval' },
              { c: 'W-4 update', s: 'done', st: 'Applied' },
            ],
          },
        ],
      },
    ],
  },
  admin: {
    label: 'Payroll Administrator',
    who: 'Sam Rivera',
    ctx: 'Payroll Control Center',
    steps: [
      {
        title: 'Payroll Control Center',
        tag: 'Home',
        tagClass: 'home',
        crumb: 'PCC',
        intro: 'Your command center for the payroll cycle. KPIs show where this run stands; open a process to drive it forward.',
        blocks: [
          {
            t: 'kpis',
            items: [
              { kv: '1,284', kl: 'Employees in scope' },
              { kv: '7', kl: 'Open alerts', tone: 'warn' },
              { kv: '2', kl: 'Errors to resolve', tone: 'err' },
              { kv: 'Jun 20', kl: 'Scheduled pay date' },
            ],
          },
          {
            t: 'tiles',
            items: [
              { i: '▶️', tt: 'Payroll Process', ts: 'Run & monitor' },
              { i: '⚠️', tt: 'Alerts & Validation', ts: '7 open' },
              { i: '💸', tt: 'Off-Cycle Workbench', ts: '22 queued' },
              { i: '📊', tt: 'Reports & Statutory', ts: 'Period reporting' },
            ],
          },
        ],
      },
      {
        title: 'Select Payroll Area & Period',
        tag: 'Process',
        crumb: 'Process',
        intro: 'Choose the population and period to process. The control record governs which period is open.',
        blocks: [
          {
            t: 'fields',
            title: 'Run scope',
            items: [
              F('Payroll area', 'US01 — Bi-weekly', { filled: true, req: true }),
              F('Country grouping', '10 — United States', { filled: true }),
              F('Payroll period', '12 / 2025 (Jun 7 – Jun 20)', { filled: true, req: true, full: true }),
              F('Pay date', '06/20/2025', { filled: true }),
              F('Run type', 'Productive', { filled: true }),
            ],
          },
        ],
      },
      {
        title: 'Start & Lock Master Data',
        tag: 'Process',
        crumb: 'Process',
        intro: "Release the period for processing. Master data is locked so changes can't slip in mid-run.",
        blocks: [
          {
            t: 'checklist',
            title: 'Pre-run readiness',
            items: [
              { c: "Control record set to 'Released for payroll'", s: 'done', st: 'Done' },
              { c: 'Master data locked for period 12', s: 'done', st: 'Locked' },
              { c: 'Time evaluation completed', s: 'done', st: 'Done' },
              { c: 'Retro accounting window checked', s: 'prog', st: 'Reviewing' },
            ],
          },
          {
            t: 'note',
            text: 'Once released, employee edits (bank, tax, comp) queue for the <b>next</b> period or trigger retro calculation.',
          },
        ],
      },
      {
        title: 'Run Productive Payroll',
        tag: 'Run',
        tagClass: 'run',
        crumb: 'Process',
        intro: 'Execute the run. Start with a simulation, review results, then run productive.',
        blocks: [
          {
            t: 'kpis',
            items: [
              { kv: '1,284', kl: 'Records selected' },
              { kv: '1,275', kl: 'Calculated OK', tone: 'ok' },
              { kv: '9', kl: 'Rejected', tone: 'err' },
              { kv: '00:04:12', kl: 'Run time' },
            ],
          },
          {
            t: 'choices',
            title: 'Run mode',
            items: [
              { l: 'Simulation', s: 'No results stored — safe to preview', sel: false },
              { l: 'Productive run', s: 'Stores results for posting and payment', sel: true },
            ],
          },
        ],
      },
      {
        title: 'Alerts & Validation',
        tag: 'Review',
        tagClass: 'review',
        crumb: 'Alerts',
        intro: 'The validation rules surface anything that needs a human. Clear errors before you can exit the run.',
        blocks: [
          {
            t: 'alerts',
            items: [
              { sev: 'error', icon: '⛔', title: 'Negative net pay — 1 employee', sub: 'Retro deduction exceeds current gross · Emp 10293', ab: 'Error' },
              { sev: 'error', icon: '⛔', title: 'Missing bank details — 1 employee', sub: 'Payment method not maintained · Emp 10477', ab: 'Error' },
              { sev: 'warn', icon: '⚠️', title: 'Retroactive changes — 14 employees', sub: 'Master data changed affecting a prior period', ab: 'Warning' },
              { sev: 'warn', icon: '⚠️', title: 'Tax model incomplete — 3 employees', sub: 'Withholding configuration needs review', ab: 'Warning' },
              { sev: 'info', icon: 'ℹ️', title: 'Off-cycle bonuses pending — 22 employees', sub: 'Queued in the off-cycle workbench', ab: 'Info' },
            ],
          },
        ],
      },
      {
        title: 'Resolve Exceptions & Re-run',
        tag: 'Process',
        crumb: 'Process',
        intro: 'Fix the flagged records, then re-run just the affected employees.',
        blocks: [
          {
            t: 'checklist',
            title: 'Corrections',
            items: [
              { c: 'Emp 10293 — adjust retro deduction split', s: 'prog', st: 'In progress' },
              { c: 'Emp 10477 — request bank details from employee', s: 'todo', st: 'Action sent' },
              { c: 'Re-run 2 corrected employees', s: 'todo', st: 'Pending' },
              { c: 'Re-validate alert list', s: 'todo', st: 'Pending' },
            ],
          },
          {
            t: 'note',
            text: 'Re-running targets only the corrected population, so the rest of the run stays untouched.',
          },
        ],
      },
      {
        title: 'Off-Cycle / One-Time Payments',
        tag: 'Process',
        crumb: 'Off-cycle',
        intro: 'Process payments outside the regular run — bonuses, corrections, or final pay.',
        blocks: [
          {
            t: 'fields',
            title: 'Off-cycle payment',
            items: [
              F('Payment type', 'Bonus (one-time)', { filled: true, req: true }),
              F('Reason', 'Q2 spot award', { filled: true }),
              F('Payment date', '06/24/2025', { filled: true }),
              F('Employees', '22 selected', { filled: true }),
              F('Total gross', '$33,000.00', { filled: true, full: true }),
            ],
          },
        ],
      },
      {
        title: 'Exit Payroll & Lock Period',
        tag: 'Process',
        crumb: 'Process',
        intro: 'Confirm the run is complete and accurate, then exit. This closes the period for processing.',
        blocks: [
          {
            t: 'review',
            title: 'Run summary',
            rows: [
              ['Employees paid', '1,284'],
              ['Errors remaining', '0'],
              ['Total gross', '$5.21M'],
              ['Total net', '$3.74M'],
              ['Control record', 'Exit payroll'],
            ],
          },
          {
            t: 'esign',
            sig: 'Sam Rivera',
            lbl: 'I confirm the payroll results are complete and approved to exit.',
          },
        ],
      },
      {
        title: 'Posting to Finance (FI)',
        tag: 'Process',
        crumb: 'Posting',
        intro: 'Post the payroll results to the general ledger. Review the posting document before releasing.',
        blocks: [
          {
            t: 'checklist',
            title: 'Posting run',
            items: [
              { c: 'Create posting run', s: 'done', st: 'Done' },
              { c: 'Review posting document & accounts', s: 'prog', st: 'Reviewing' },
              { c: 'Release to Finance', s: 'todo', st: 'Pending' },
            ],
          },
          {
            t: 'review',
            title: 'Posting document',
            rows: [
              ['Document number', '1900004821'],
              ['Debit — wages & taxes', '$5,210,440.00'],
              ['Credit — net payable', '$3,742,118.00'],
              ['Status', 'Awaiting release'],
            ],
          },
        ],
      },
      {
        title: 'Bank Transfer / Payment File',
        tag: 'Process',
        crumb: 'Payment',
        intro: 'Generate the payment medium (ACH / DME file) and release it to the bank by the cut-off.',
        blocks: [
          {
            t: 'fields',
            title: 'Payment run',
            items: [
              F('Payment method', 'ACH — direct deposit', { filled: true }),
              F('House bank', 'Northwind Operating', { filled: true }),
              F('Value date', '06/20/2025', { filled: true }),
              F('File format', 'NACHA / DMEE', { filled: true }),
              F('Payments', '1,284 · $3,742,118.00', { filled: true, full: true }),
            ],
          },
          {
            t: 'esign',
            sig: 'Sam Rivera',
            lbl: 'I authorize release of this payment file to the bank.',
          },
        ],
      },
      {
        title: 'Process Complete',
        tag: 'Done',
        tagClass: 'done',
        crumb: 'Done',
        intro: '',
        blocks: [
          {
            t: 'complete',
            h: 'Period 12 payroll closed',
            p: 'Results are posted to Finance and the payment file is released. Payslips and statutory reports are generated next.',
          },
          {
            t: 'checklist',
            title: 'Post-run tasks',
            items: [
              { c: 'Publish remuneration statements (payslips)', s: 'prog', st: 'Generating' },
              { c: 'Run statutory & period reports', s: 'todo', st: 'Scheduled' },
              { c: 'Archive run log', s: 'todo', st: 'Pending' },
            ],
          },
        ],
      },
    ],
  },
  manager: {
    label: 'Manager',
    who: 'Taylor Brooks',
    ctx: 'Manager self-service',
    steps: [
      {
        title: 'Approvals — Home',
        tag: 'Home',
        tagClass: 'home',
        crumb: 'Inbox',
        intro: 'Items that feed payroll route to you for sign-off. Clear them before the payroll period locks.',
        blocks: [
          {
            t: 'tiles',
            items: [
              { i: '⏱️', tt: 'Time & Overtime', ts: '2 to approve', badge: '2' },
              { i: '🎁', tt: 'One-Time Payments', ts: '1 bonus request', badge: '1' },
              { i: '🏦', tt: 'Pay / Bank Changes', ts: '1 change', badge: '1' },
              { i: '💵', tt: 'Team Compensation', ts: 'Read-only' },
            ],
          },
          {
            t: 'note',
            warn: true,
            text: 'Approvals submitted after the <b>period lock</b> shift to the next payroll run, so don’t sit on them.',
          },
        ],
      },
      {
        title: 'Approve Time & Overtime',
        tag: 'Review',
        tagClass: 'review',
        crumb: 'Approvals',
        intro: 'Approved time flows into the payroll calculation. Review hours before approving.',
        blocks: [
          {
            t: 'checklist',
            title: 'Awaiting approval',
            items: [
              { c: 'Jordan Avery — 4.0 hrs overtime (Jun 18)', s: 'prog', st: 'Approve' },
              { c: 'Lee Park — 2.5 hrs overtime (Jun 19)', s: 'todo', st: 'Approve' },
            ],
          },
          {
            t: 'actions',
            items: [
              { label: 'Approve all', kind: 'primary' },
              { label: 'Send back', kind: 'ghost' },
            ],
          },
        ],
      },
      {
        title: 'Approve One-Time Payment',
        tag: 'Review',
        tagClass: 'review',
        crumb: 'Approvals',
        intro: 'A bonus or spot award needs your sign-off before it reaches the off-cycle workbench.',
        blocks: [
          {
            t: 'review',
            title: 'Q2 spot award',
            rows: [
              ['Employee', 'Jordan Avery'],
              ['Payment type', 'Bonus (one-time)'],
              ['Amount', '$1,500.00'],
              ['Reason', 'Exceptional launch support'],
              ['Pay date', 'Jun 24, 2025'],
            ],
          },
          {
            t: 'actions',
            items: [
              { label: 'Approve', kind: 'primary' },
              { label: 'Decline', kind: 'ghost' },
            ],
          },
        ],
      },
      {
        title: 'Approve Pay / Bank Change',
        tag: 'Review',
        tagClass: 'review',
        crumb: 'Approvals',
        intro: 'An employee updated their payment information. Confirm it before payroll applies the change.',
        blocks: [
          {
            t: 'review',
            title: 'Direct deposit change',
            rows: [
              ['Employee', 'Jordan Avery'],
              ['Change', 'New main bank account'],
              ['Account (masked)', '•••••4821 · Checking'],
              ['Effective', 'Next pay period'],
            ],
          },
          {
            t: 'note',
            text: 'You’re confirming the <b>request is legitimate</b>; payroll validates the bank details before activation.',
          },
          {
            t: 'actions',
            items: [
              { label: 'Approve', kind: 'primary' },
              { label: 'Send back', kind: 'ghost' },
            ],
          },
        ],
      },
      {
        title: 'Review Team Compensation',
        tag: 'Review',
        tagClass: 'review',
        crumb: 'Team',
        intro: 'A read-only view of your team’s pay components for context. Changes go through HR.',
        blocks: [
          {
            t: 'checklist',
            title: 'Analytics team',
            items: [
              { c: 'Jordan Avery — Product Analyst', s: 'done', st: '$92,000' },
              { c: 'Lee Park — Senior Analyst', s: 'done', st: '$108,000' },
              { c: 'Dana Cole — Analyst', s: 'done', st: '$84,000' },
            ],
          },
        ],
      },
      {
        title: 'All caught up',
        tag: 'Done',
        tagClass: 'done',
        crumb: 'Done',
        intro: '',
        blocks: [
          {
            t: 'complete',
            h: 'Your payroll approvals are clear',
            p: 'Time, the bonus request, and the bank change are all signed off and will flow into this period’s run.',
          },
          {
            t: 'note',
            text: 'Tip: the next payroll period locks on <b>Jun 18</b>. New requests after that move to the following run.',
          },
        ],
      },
    ],
  },
}

export const RUN_PERSONAS: Record<PersonaKey, Persona> = {
  employee: {
    label: 'Employee',
    who: 'Alex Morgan',
    ctx: 'Employee self-service',
    steps: [
      {
        title: 'My Pay — Home',
        tag: 'Home',
        tagClass: 'home',
        crumb: 'Home',
        intro: 'Payroll lives in your People Profile and the launchpad tiles below. Open any tile to view or update your pay information.',
        blocks: [
          {
            t: 'tiles', items: [
              { i: '🧾', tt: 'Latest Pay Statement', ts: 'Pay date Jun 20' },
              { i: '📜', tt: 'Pay Statement History', ts: 'View past payslips' },
              { i: '🏦', tt: 'Payment Information', ts: 'Direct deposit' },
              { i: '🧾', tt: 'Tax Withholding', ts: 'Form W-4' },
              // { i: '📈', tt: 'Deductions', ts: 'Benefits & more' },
              {
                i: '📉',
                tt: 'Deductions',
                ts: 'Benefits & more',
              },
              {
                i: '📄',
                tt: 'Year-End Documents',
                ts: 'W-2 & tax forms',
              },
              {
                i: '💵',
                tt: 'Compensation',
                ts: 'Pay components',
              },
              {
                i: '✅',
                tt: 'To-Do',
                ts: 'Tax form to confirm',
                badge: '1',
              },
            ]
          },
        ],
      },
      {
        title: 'Latest Pay Statement',
        tag: 'Pay',
        crumb: 'Pay',
        intro: 'Your most recent pay statement and quick actions.',
        blocks: [
          {
            t: 'payslip', period: 'Jun 7 – Jun 20, 2025 · Period 12 of 26', payDate: 'Fri, Jun 20, 2025', status: 'Paid', earnings: [
              { label: 'Base Salary', cur: '$3,538.46', ytd: '$42,461.52' },
              { label: 'Overtime', cur: '$145.00', ytd: '$612.00' },
            ], gross: { cur: '$3,733.46', ytd: '$43,673.52' }, deductions: [
              { label: 'Federal Income Tax', cur: '$512.10', ytd: '$6,021.40' },
            ], ded: { cur: '$1,126.68', ytd: '$13,253.71' }, net: { cur: '$2,606.78', ytd: '$30,419.81' }
          },
          { t: 'actions', items: [{ label: 'Download PDF', kind: 'primary' }, { label: 'Email to me', kind: 'ghost' }] },
        ],
      },
      {
        title: 'Pay Statement History',
        tag: 'Pay',
        crumb: 'Pay',
        intro: 'Every payslip on record. Open or download any period.',
        blocks: [
          {
            t: 'docs',
            items: [
              {
                n: 'June 20, 2025',
                d: 'Period 12 · Net $2,606.78',
                badge: 'ok',
                bl: 'View',
              },
              {
                n: 'June 6, 2025',
                d: 'Period 11 · Net $2,584.12',
                badge: 'ok',
                bl: 'View',
              },
              {
                n: 'May 23, 2025',
                d: 'Period 10 · Net $2,584.12',
                badge: 'ok',
                bl: 'View',
              },
              {
                n: 'May 9, 2025',
                d: 'Period 9 · Net $2,571.40',
                badge: 'ok',
                bl: 'View',
              },
            ],
          },
        ],
      },
      {
        title: 'Payment Information',
        tag: 'Task',
        tagClass: 'task',
        crumb: 'My Info',
        intro: 'Manage your bank and payment preferences used by payroll.',
        blocks: [
          {
            t: 'fields', title: 'Bank account', items: [
              { label: 'Account', val: '••••4821', filled: true },
              { label: 'Routing', val: '021000021', filled: true },
            ]
          },
        ],
      },
      {
        title: 'Compensation Information',
        tag: 'Review',
        tagClass: 'review',
        crumb: 'My Info',
        intro:
          'Your current pay components, as configured by HR. This view is read-only.',
        blocks: [
          {
            t: 'review',
            title: 'Pay components',
            rows: [
              ['Annual base salary', '$92,000.00'],
              ['Pay frequency', 'Bi-weekly (26)'],
              ['Compensation plan', 'Analytics Band 3'],
              ['Remote allowance', '$50.00 / period'],
              ['Last change', 'Effective Jan 1, 2025'],
            ],
          },
        ],
      },
      {
        title: 'Tax Withholding (Form W-4)',
        tag: 'Task',
        tagClass: 'task',
        crumb: 'Pay',
        intro: 'Tell payroll how much federal tax to withhold.',
        blocks: [
          {
            t: 'fields', title: 'Federal elections', items: [
              { label: 'Filing status', val: 'Single or married filing separately', filled: true, full: true },
              { label: 'Dependents amount', val: '$0.00', filled: true },
            ]
          },
        ],
      },
      {
        title: 'Deductions',
        tag: 'Review',
        tagClass: 'review',
        crumb: 'Pay',
        intro: 'A breakdown of what’s deducted from your pay each period.',
        blocks: [
          {
            t: 'checklist', title: 'Recurring deductions', items: [
              { c: '401(k) retirement — 5% pre-tax', s: 'done', st: '$186.67' },
              { c: 'Medical & dental premium', s: 'done', st: '$142.30' },
            ]
          },
        ],
      },
      {
        title: 'Year-End Documents',
        tag: 'Task',
        tagClass: 'task',
        crumb: 'Documents',
        intro: 'Access your annual tax statements and choose how you’d like to receive them.',
        blocks: [
          {
            t: 'docs',
            items: [
              { n: 'Form W-2 — 2024', d: 'Available · issued Jan 28, 2025', badge: 'ok', bl: 'Download' },
              { n: 'Form W-2 — 2023', d: 'Available', badge: 'ok', bl: 'Download' },
            ],
          },
          {
            t: 'choices',
            title: 'Delivery preference',
            items: [
              { l: 'Electronic only (recommended)', s: 'Get notified when your W-2 is ready', sel: true },
              { l: 'Electronic and mailed paper copy', s: '', sel: false },
            ],
          },
        ],
      },
      {
        title: 'All set',
        tag: 'Done',
        tagClass: 'done',
        crumb: 'Done',
        intro: '',
        blocks: [
          { t: 'complete', h: 'Your payroll information is up to date', p: 'You can return to any tile anytime.' },
        ],
      },
    ],
  },
  admin: OUTPUT_PERSONAS.admin,
  manager: OUTPUT_PERSONAS.manager,
}

export const PERSONAS = OUTPUT_PERSONAS
